###
on:
  workflow_dispatch:
  push:
    paths:
      - src

permissions:
  contents: write

jobs:
  build:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Build prepare checkout
        uses: actions/checkout@v4
        with:
          repository: "NguyenDuck/nguyenduck.io.vn-build"
          path: "deploy"

      - name: Build
        run: npm run build

      - name: Deploy to repository
        run: |
          cp .cpanel.yml deploy -rf
          cp build deploy -rf
          cd deploy
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "Update website"
          git push origin dev
